imageRegistry: ghcr.io/patsevanton/holmesgpt-mem0-qdrant-radar
imageTag: "1.1.0"
imagePullPolicy: IfNotPresent

apps:
  - name: go-1
    replicaCount: 1
    port: 8080
    env:
      LISTEN_ADDR: "8080"
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi