{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    {{- include "bench-apps.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      name: http
---
{{- end }}
